import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, AlertTriangle, Users, Eye } from 'lucide-react';

export default function Terms() {
  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      
      {/* Background Ambience */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-[#00FF41]/5 rounded-full blur-[100px] mix-blend-screen opacity-50" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-[#00E5FF]/5 rounded-full blur-[100px] mix-blend-screen opacity-50" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-12">
        
        {/* Header */}
        <div className="mb-12">
          <Link 
            to="/signup" 
            className="inline-flex items-center gap-2 text-zinc-400 hover:text-[#00FF41] transition-colors mb-6 group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            Back to Sign Up
          </Link>
          
          <div className="flex items-center gap-4 mb-4">
            <FileText className="w-10 h-10 text-[#00FF41]" />
            <h1 className="text-4xl font-bold">Terms of Service</h1>
          </div>
          
          <p className="text-zinc-400 text-sm">
            Last Updated: February 3, 2026
          </p>
        </div>

        {/* Critical Disclaimer Banner */}
        <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-6 mb-8 flex items-start gap-4">
          <AlertTriangle className="w-6 h-6 text-yellow-500 shrink-0 mt-1" />
          <div>
            <h3 className="text-yellow-500 font-bold text-lg mb-2">Important Notice</h3>
            <p className="text-zinc-300 leading-relaxed">
              This platform is an AI-powered analysis tool. The information provided is for research purposes only 
              and does not constitute professional investment advice, financial advice, or any recommendation to buy, 
              sell, or hold securities or investments.
            </p>
          </div>
        </div>

        {/* Terms Content */}
        <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-xl p-8 space-y-8">
          
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing, registering for, or using "The Roots" ("the System", "we", "us"), you acknowledge that 
              you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to 
              these terms, you must not use the System.
            </p>
          </Section>

          <Section title="2. Nature of Services (AI Disclaimer)">
            <p>
              The System utilizes advanced Artificial Intelligence (AI) and Large Language Models (LLMs) to analyze 
              startup materials and market data. You explicitly acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>
                <strong>AI Limitations:</strong> AI technology is experimental and probabilistic in nature. 
                The System may produce output that is inaccurate, incomplete, or misleading ("hallucinations").
              </li>
              <li>
                <strong>No Human Verification:</strong> The reports and scores generated by the System are automated 
                and <strong>have not been verified by human analysts</strong>.
              </li>
              <li>
                <strong>"As-Is" Basis:</strong> The Service is provided on an "AS IS" and "AS AVAILABLE" basis. 
                We make no warranties regarding the accuracy, reliability, or completeness of the data.
              </li>
            </ul>
          </Section>

          <Section title="3. No Financial or Investment Advice">
            <div className="bg-yellow-500/10 border-l-4 border-yellow-500 p-4 rounded-r-lg mt-3">
              <p className="font-bold text-yellow-500 mb-2">CRITICAL:</p>
              <p className="mb-2">The System is a research and decision-support tool only.</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>
                  Nothing in the System constitutes investment advice, financial advice, trading advice, or a 
                  recommendation to buy or sell any security or invest in any entity.
                </li>
                <li>
                  You are solely responsible for your investment decisions. You should conduct your own independent 
                  due diligence and consult with a certified financial advisor before making any financial decisions.
                </li>
                <li>
                  We accept no liability for any loss or damage resulting from your reliance on the System's analysis.
                </li>
              </ul>
            </div>
          </Section>

          {/* 🔴 CRITICAL SECTION - PUBLIC SHARING */}
          <Section 
            title="4. User Content, Data & Transparency" 
            icon={<Users className="w-6 h-6 text-[#00E5FF]" />}
          >
            <ul className="space-y-4">
              <li>
                <strong>License to Process:</strong> You retain ownership of the documents (e.g., pitch decks) 
                you upload. By uploading content, you grant us a license to process the data to generate reports.
              </li>
              
              {/* 🚨 THE CRITICAL PUBLIC SHARING CLAUSE */}
              <li>
                <div className="bg-red-500/10 border-l-4 border-red-500 p-4 rounded-r-lg">
                  <div className="flex items-start gap-3">
                    <Eye className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
                    <div>
                      <p className="font-bold text-red-400 mb-2">
                        Public Visibility of Analyses (Crucial):
                      </p>
                      <p className="text-zinc-300 leading-relaxed">
                        <strong>PLEASE NOTE:</strong> "The Roots" is a <strong>collaborative knowledge-sharing platform</strong>. 
                        <span className="text-red-300 font-semibold"> You acknowledge and agree that any analysis, report, 
                        or score generated by the System based on your inputs will be visible and accessible to ALL other 
                        users of the System.</span>
                      </p>
                    </div>
                  </div>
                </div>
              </li>
              
              <li>
                <strong>Confidentiality Warning:</strong> Do not upload documents containing confidential, proprietary, 
                or sensitive information that you are legally restricted from sharing or having analyzed publicly. 
                We accept no liability for the public exposure of insights derived from confidential documents uploaded by you.
              </li>
            </ul>
          </Section>

          <Section title="5. Limitation of Liability">
            <p className="font-bold text-[#00FF41] uppercase text-sm leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL "THE ROOTS", ITS DEVELOPERS, OR AFFILIATES 
              BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING 
              WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM 
              YOUR USE OF THE SYSTEM.
            </p>
          </Section>

          <Section title="6. Indemnification">
            <p>
              You agree to defend, indemnify, and hold harmless "The Roots" and its team from any claims, damages, 
              obligations, losses, liabilities, costs, or debt arising from your use of the System or your violation 
              of any term of these Terms of Service.
            </p>
          </Section>

          <Section title="7. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Israel. 
              Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the competent 
              courts in Jerusalem, Israel.
            </p>
          </Section>

        </div>

        {/* Final Acknowledgment */}
        <div className="mt-8 p-6 bg-[#00FF41]/5 border border-[#00FF41]/20 rounded-xl">
          <p className="text-zinc-300 text-sm leading-relaxed">
            <span className="font-bold text-[#00FF41]">By checking the acceptance box during registration, you confirm that:</span>
            <br />
            • You have read and understood these Terms of Service
            <br />
            • You accept all terms, conditions, disclaimers, and limitations
            <br />
            • You understand the System is AI-powered and may contain errors
            <br />
            • You will not rely solely on the System for investment decisions
            <br />
            • You accept full responsibility for your investment decisions
            <br />
            • <strong className="text-red-300">You understand that all reports are publicly visible to other users</strong>
          </p>
        </div>

        {/* Back Button */}
        <div className="mt-12 text-center">
          <Link 
            to="/signup" 
            className="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-[#00FF41] to-[#00E5FF] text-black font-bold rounded-lg 
              hover:scale-105 transition-all duration-300 shadow-[0_0_20px_rgba(0,255,65,0.2)]"
          >
            <ArrowLeft className="w-5 h-5" />
            Return to Sign Up
          </Link>
        </div>

      </div>
    </div>
  );
}

const Section = ({ title, icon, children }) => (
  <div>
    <h2 className="text-xl font-bold text-white mb-3 flex items-center gap-2">
      {icon || <span className="text-[#00E5FF]">→</span>}
      {title}
    </h2>
    <div className="text-zinc-300 space-y-3 leading-relaxed">
      {children}
    </div>
  </div>
);