import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, AlertTriangle } from 'lucide-react';

export default function Terms() {
  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      
      {/* Background Ambience */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-[#00FF41]/5 rounded-full blur-[100px] mix-blend-screen opacity-50" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-[#00E5FF]/5 rounded-full blur-[100px] mix-blend-screen opacity-50" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-12">
        
        {/* Header */}
        <div className="mb-12">
          <Link 
            to="/signup" 
            className="inline-flex items-center gap-2 text-zinc-400 hover:text-[#00FF41] transition-colors mb-6 group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            Back to Sign Up
          </Link>
          
          <div className="flex items-center gap-4 mb-4">
            <FileText className="w-10 h-10 text-[#00FF41]" />
            <h1 className="text-4xl font-bold">Terms of Use</h1>
          </div>
          
          <p className="text-zinc-400 text-sm">
            Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        {/* Critical Disclaimer Banner */}
        <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-6 mb-8 flex items-start gap-4">
          <AlertTriangle className="w-6 h-6 text-yellow-500 shrink-0 mt-1" />
          <div>
            <h3 className="text-yellow-500 font-bold text-lg mb-2">Important Notice</h3>
            <p className="text-zinc-300 leading-relaxed">
              This platform is an AI-powered analysis tool. The information provided is for research purposes only 
              and does not constitute professional investment advice, financial advice, or any recommendation to buy, 
              sell, or hold securities or investments.
            </p>
          </div>
        </div>

        {/* Terms Content */}
        <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-xl p-8 space-y-8">
          
          <Section title="1. Acceptance of Terms">
            <p>
              By creating an account and using The Roots platform ("Service"), you agree to be bound by these Terms of Use. 
              If you do not agree to these terms, you may not use the Service.
            </p>
          </Section>

          <Section title="2. AI-Generated Content Disclaimer">
            <p>
              The Service uses artificial intelligence and machine learning algorithms to analyze startup information 
              and generate investment analysis reports. You acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>AI-generated content may contain errors, inaccuracies, or incomplete information</li>
              <li>Analysis results are probabilistic and based on available data at the time of generation</li>
              <li>The system cannot guarantee accuracy, completeness, or reliability of any analysis</li>
              <li>AI models may have inherent biases or limitations in understanding context</li>
            </ul>
          </Section>

          <Section title="3. Not Investment Advice">
            <p className="font-semibold text-[#00FF41]">
              THE SERVICE DOES NOT PROVIDE INVESTMENT ADVICE, FINANCIAL ADVICE, OR RECOMMENDATIONS.
            </p>
            <p className="mt-3">
              All analyses, scores, reports, and recommendations generated by the Service are for informational and 
              research purposes only. They should not be construed as:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>Professional investment advice</li>
              <li>Financial or legal counsel</li>
              <li>Recommendations to buy, sell, or hold any security</li>
              <li>Endorsement of any startup, company, or investment opportunity</li>
            </ul>
          </Section>

          <Section title="4. User Responsibility">
            <p>
              You are solely responsible for:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>All investment decisions you make based on or influenced by the Service</li>
              <li>Conducting your own due diligence and research</li>
              <li>Consulting with qualified financial, legal, and tax advisors before making investment decisions</li>
              <li>Verifying all information independently before taking any action</li>
              <li>Any losses, damages, or consequences resulting from your use of the Service</li>
            </ul>
          </Section>

          <Section title="5. As-Is Service">
            <p>
              The Service is provided "AS IS" and "AS AVAILABLE" without any warranties of any kind, either express or implied, 
              including but not limited to:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>Warranties of merchantability or fitness for a particular purpose</li>
              <li>Warranties regarding accuracy, reliability, or completeness of information</li>
              <li>Warranties that the Service will be uninterrupted, secure, or error-free</li>
              <li>Warranties regarding data quality, analysis quality, or report quality</li>
            </ul>
          </Section>

          <Section title="6. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, The Roots and its creators shall not be liable for any:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>Investment losses or financial damages</li>
              <li>Indirect, incidental, special, consequential, or punitive damages</li>
              <li>Loss of profits, revenue, data, or business opportunities</li>
              <li>Damages resulting from errors, omissions, or inaccuracies in the Service</li>
              <li>Damages resulting from reliance on AI-generated content</li>
            </ul>
          </Section>

          <Section title="7. Data Privacy">
            <p>
              We collect and process user data and startup information uploaded to the platform. By using the Service, 
              you consent to our collection, use, and processing of your data in accordance with our Privacy Policy.
            </p>
          </Section>

          <Section title="8. Intellectual Property">
            <p>
              You retain ownership of any content you upload. However, you grant us a license to process, analyze, 
              and generate reports based on your uploaded content. The AI-generated analyses and reports are provided 
              for your use but remain subject to these Terms.
            </p>
          </Section>

          <Section title="9. Prohibited Uses">
            <p>
              You may not use the Service to:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3 ml-4">
              <li>Make investment decisions solely based on AI-generated reports</li>
              <li>Provide investment advice to third parties using Service outputs</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Upload false, misleading, or fraudulent information</li>
              <li>Attempt to manipulate or game the analysis system</li>
            </ul>
          </Section>

          <Section title="10. Modification of Terms">
            <p>
              We reserve the right to modify these Terms at any time. Your continued use of the Service after 
              changes constitutes acceptance of the modified Terms.
            </p>
          </Section>

          <Section title="11. Termination">
            <p>
              We may terminate or suspend your access to the Service at any time, with or without cause or notice, 
              including for violation of these Terms.
            </p>
          </Section>

          <Section title="12. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws, without regard to 
              conflict of law principles.
            </p>
          </Section>

          <Section title="13. Contact Information">
            <p>
              For questions about these Terms, please contact us through the platform support system.
            </p>
          </Section>

        </div>

        {/* Final Acknowledgment */}
        <div className="mt-8 p-6 bg-[#00FF41]/5 border border-[#00FF41]/20 rounded-xl">
          <p className="text-zinc-300 text-sm leading-relaxed">
            <span className="font-bold text-[#00FF41]">By checking the acceptance box during registration, you confirm that:</span>
            <br />
            • You have read and understood these Terms of Use
            <br />
            • You accept all terms, conditions, disclaimers, and limitations
            <br />
            • You understand the Service is AI-powered and may contain errors
            <br />
            • You will not rely solely on the Service for investment decisions
            <br />
            • You accept full responsibility for your investment decisions
          </p>
        </div>

        {/* Back Button */}
        <div className="mt-12 text-center">
          <Link 
            to="/signup" 
            className="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-[#00FF41] to-[#00E5FF] text-black font-bold rounded-lg 
              hover:scale-105 transition-all duration-300 shadow-[0_0_20px_rgba(0,255,65,0.2)]"
          >
            <ArrowLeft className="w-5 h-5" />
            Return to Sign Up
          </Link>
        </div>

      </div>
    </div>
  );
}

const Section = ({ title, children }) => (
  <div>
    <h2 className="text-xl font-bold text-white mb-3 flex items-center gap-2">
      <span className="text-[#00E5FF]">→</span> {title}
    </h2>
    <div className="text-zinc-300 space-y-3 leading-relaxed">
      {children}
    </div>
  </div>
);